#!/usr/bin/env node
/**
 * Weekly Security Report Generator
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const WORKSPACE = process.env.WORKSPACE || '/Users/openclaw/.openclaw/workspace';
const SECURITY_DIR = path.join(WORKSPACE, 'data', 'security');
const REPORTS_DIR = path.join(SECURITY_DIR, 'weekly-reports');

// Ensure reports directory exists
if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

const today = new Date().toISOString().split('T')[0];

console.log('🔐 Generating Weekly Security Report...\n');

// Run all scans
console.log('Running credential scan...');
try {
  execSync('node scripts/security/credential-scan.js', { 
    cwd: WORKSPACE, 
    stdio: 'pipe' 
  });
} catch (e) { /* may exit non-zero if findings */ }

console.log('Running dependency audit...');
try {
  execSync('node scripts/security/dependency-audit.js', { 
    cwd: WORKSPACE, 
    stdio: 'pipe' 
  });
} catch (e) { /* may exit non-zero if findings */ }

console.log('Running permission check...');
try {
  execSync('node scripts/security/permission-check.js', { 
    cwd: WORKSPACE, 
    stdio: 'pipe' 
  });
} catch (e) { /* may exit non-zero if findings */ }

// Load results
let credAudit = { summary: { critical: 0, high: 0, medium: 0 } };
let vulnScan = { summary: { critical: 0, high: 0 } };

try {
  credAudit = JSON.parse(fs.readFileSync(path.join(SECURITY_DIR, 'credential-audit.json')));
} catch (e) {}

try {
  vulnScan = JSON.parse(fs.readFileSync(path.join(SECURITY_DIR, 'vulnerability-scan.json')));
} catch (e) {}

// Calculate security score (0-100)
let score = 100;
score -= credAudit.summary.critical * 20;
score -= credAudit.summary.high * 10;
score -= credAudit.summary.medium * 5;
score -= credAudit.summary.badPermissions * 5;
score -= vulnScan.summary.critical * 15;
score -= vulnScan.summary.high * 7;
score = Math.max(0, score);

// Generate report
const report = `# 🔐 Weekly Security Report
**Date:** ${today}
**Generated by:** Sentinel (CISO Agent)

---

## Security Score: ${score}/100 ${score >= 80 ? '✅' : score >= 60 ? '⚠️' : '🔴'}

---

## Credential Security

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${credAudit.summary.critical || 0} |
| 🟠 High | ${credAudit.summary.high || 0} |
| 🟡 Medium | ${credAudit.summary.medium || 0} |
| ⚠️ Bad Permissions | ${credAudit.summary.badPermissions || 0} |

## Dependency Vulnerabilities

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${vulnScan.summary.critical || 0} |
| 🟠 High | ${vulnScan.summary.high || 0} |

## Recommendations

${score < 80 ? `
### Immediate Actions Required:
${credAudit.summary.critical > 0 ? '- [ ] Review and rotate exposed credentials\n' : ''}${credAudit.summary.badPermissions > 0 ? '- [ ] Fix file permissions on sensitive files\n' : ''}${vulnScan.summary.critical > 0 ? '- [ ] Update packages with critical vulnerabilities\n' : ''}
` : '- No immediate actions required. Continue monitoring.'}

## Assets Monitored

- Workspace files and scripts
- Credential storage (${credAudit.credentialAudit?.length || 0} files)
- Node.js dependencies (${vulnScan.totalProjects || 0} projects)
- API integrations

## Next Review

${new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]}

---

*Report generated automatically by Sentinel*
`;

// Save report
const reportPath = path.join(REPORTS_DIR, `security-report-${today}.md`);
fs.writeFileSync(reportPath, report);

console.log(`\n✅ Report saved to: ${reportPath}`);
console.log(`\n📊 Security Score: ${score}/100`);

// Output for Telegram
console.log('\n--- TELEGRAM SUMMARY ---');
console.log(`🔐 Weekly Security Report — ${today}`);
console.log(`Score: ${score}/100 ${score >= 80 ? '✅' : score >= 60 ? '⚠️' : '🔴'}`);
console.log(`Credentials: ${credAudit.summary.critical || 0} critical, ${credAudit.summary.high || 0} high`);
console.log(`Dependencies: ${vulnScan.summary.critical || 0} critical, ${vulnScan.summary.high || 0} high`);
if (score < 80) {
  console.log(`⚠️ Action needed — see full report`);
}
