/**
 * VentureOS API Module — CR-VENTUREOS-V1
 * Venture governance system: create, stage gates, kill rules, metrics.
 * SSOT: /data/ventures/ (4 JSON files)
 * Activity: /data/mission-control/agent_activity.json
 */
'use strict';
const fs=require('fs'),path=require('path'),os=require('os');
const DATA_ROOT=path.join(os.homedir(),'.openclaw/workspace/data/ventures');
const ACTIVITY_FILE=path.join(os.homedir(),'.openclaw/workspace/data/mission-control/agent_activity.json');
const VENTURES_DIR=path.join(os.homedir(),'.openclaw/workspace/ventures');
const VALID_STAGES=['opportunity','investigation','approval','implementation','launch','killed'];
const VALID_TRANSITIONS={opportunity:['investigation','killed'],investigation:['approval','killed'],approval:['implementation','killed'],implementation:['launch','killed'],launch:['killed']};
const KILL_AUTHORIZED=['clawson','steve'];
const GATE_KEEPERS={investigation:'moonshot',approval:'clawson',implementation:'steve',launch:'codesmith'};
function readSSO(f){return JSON.parse(fs.readFileSync(path.join(DATA_ROOT,f),'utf-8'));}
function writeSSO(f,d){d.lastUpdated=new Date().toISOString();fs.writeFileSync(path.join(DATA_ROOT,f),JSON.stringify(d,null,2),'utf-8');}
function logActivity(action,desc,sev,meta){try{let d={activities:[],lastUpdated:null,total:0};try{d=JSON.parse(fs.readFileSync(ACTIVITY_FILE,'utf-8'));}catch(_){}if(!Array.isArray(d.activities))d.activities=[];const e={timestamp:new Date().toISOString(),agent:'codesmith',action,description:desc,severity:sev||'info',source:'ventureos',meta:meta||{}};d.activities.push(e);d.lastUpdated=e.timestamp;d.total=d.activities.length;fs.writeFileSync(ACTIVITY_FILE,JSON.stringify(d,null,2),'utf-8');}catch(e){console.error('[VENTUREOS] activity failed:',e.message);}}
function recalcPipeline(){const sb=readSSO('venture_scoreboard.json');const p=readSSO('venture_pipeline.json');p.stages={opportunity:0,investigation:0,approval:0,implementation:0,launch:0,killed:0};p.total=sb.ventures.length;sb.ventures.forEach(v=>{if(p.stages[v.stage]!==undefined)p.stages[v.stage]++;});p.active=p.total-p.stages.killed;const l=p.stages.launch,k=p.stages.killed,fin=l+k;p.success_rate=fin>0?+(l/fin).toFixed(2):0.0;if(!p.metrics)p.metrics={};p.metrics.kill_rate=fin>0?+(k/fin).toFixed(2):0.0;p.metrics.portfolio_mrr=sb.ventures.filter(v=>v.status==='active').reduce((s,v)=>s+((v.metrics&&v.metrics.mrr_current)||0),0);p.metrics.portfolio_mrr_target=sb.ventures.filter(v=>v.status==='active').reduce((s,v)=>s+(v.target_mrr||0),0);writeSSO('venture_pipeline.json',p);return p;}
function getGatewayRequirements(stage){const g={investigation:[{name:'memo_written',description:'Memo written',required:true},{name:'vision_clear',description:'Description present',required:true}],approval:[{name:'tam_gt_10m',description:'TAM>$10M',required:true},{name:'competitors_3',description:'3+ competitors',required:true},{name:'team_committed',description:'Team committed',required:true},{name:'budget_estimated',description:'Budget estimated',required:true}],implementation:[{name:'cr_submitted',description:'CR submitted',required:true},{name:'budget_approved',description:'Budget approved',required:true},{name:'team_assigned',description:'Team assigned',required:true}],launch:[{name:'workstreams_done',description:'MVP workstreams closed',required:true},{name:'tests_exist',description:'Tests exist',required:true},{name:'metrics_80pct',description:'Metrics >=80%',required:true}],killed:[]};return g[stage]||[];}
function validateGate(venture,next_stage){if(next_stage==='killed')return{passed:true,missing:[]};const missing=[];const reqs=getGatewayRequirements(next_stage);for(const req of reqs){if(!req.required)continue;switch(req.name){case'memo_written':if(!venture.artifacts||!venture.artifacts.memo)missing.push(req.name);break;case'vision_clear':if(!venture.description||venture.description.trim().length<10)missing.push(req.name);break;case'tam_gt_10m':if(!venture.market_opportunity||venture.market_opportunity.tam<=10000000)missing.push(req.name);break;case'competitors_3':{const c=venture.market_opportunity&&venture.market_opportunity.competitors;if(!c||c.length<3)missing.push(req.name);break;}case'team_committed':if(!venture.team||venture.team.length<1)missing.push(req.name);break;case'budget_estimated':if(!venture.financials||venture.financials.budget<=0)missing.push(req.name);break;case'cr_submitted':if(!venture.artifacts||!venture.artifacts.cr)missing.push(req.name);break;case'budget_approved':if(!venture.financials||!venture.financials.budget_approved)missing.push(req.name);break;case'team_assigned':if(!venture.team||venture.team.length<1)missing.push(req.name);break;case'tests_exist':if(!venture.artifacts||!venture.artifacts.tests)missing.push(req.name);break;case'metrics_80pct':{const m=venture.metrics||{};let ok=false;if(m.mrr_target>0&&m.mrr_current!=null)ok=(m.mrr_current/m.mrr_target)>=0.8;if(!ok&&m.customer_target>0&&m.customer_current!=null)ok=(m.customer_current/m.customer_target)>=0.8;if(!ok)missing.push(req.name);break;}case'workstreams_done':break;}}return{passed:missing.length===0,missing};}
function getVentureById(id){const sb=readSSO('venture_scoreboard.json');return sb.ventures.find(v=>v.id===id)||null;}
function getVentureDetailFull(id){const v=getVentureById(id);if(!v)return null;try{const full=readSSO('ventures.json');const f=(full.ventures||[]).find(v=>v.id===id);if(f)return{...v,...f};}catch(_){}return v;}
function getAtRisk(){const sb=readSSO('venture_scoreboard.json');const now=Date.now();const out=[];sb.ventures.forEach(v=>{if(v.status==='killed')return;const risks=[];if(v.stage_history&&v.stage_history.length>0){const curr=v.stage_history.find(h=>h.exited_at===null);if(curr&&curr.entered_at){const d=(now-new Date(curr.entered_at).getTime())/86400000;const lim=((v.timeline_weeks||8)/4)*7;if(d>lim)risks.push({type:'overdue',severity:d>lim*1.5?'critical':'warning',description:`In ${v.stage} for ${Math.round(d)} days`,days_overdue:Math.round(d-lim)});}}if(Array.isArray(v.blockers))v.blockers.forEach(b=>{if(!b.created_at)return;const age=(now-new Date(b.created_at).getTime())/86400000;if(age>30)risks.push({type:'stale_blocker',severity:'critical',description:`Blocker stale ${Math.round(age)} days`,blocker_id:b.id||null});});if(v.stage==='launch'&&v.metrics){const m=v.metrics;if(m.mrr_target>0&&m.mrr_current!=null&&m.mrr_current<m.mrr_target*0.5)risks.push({type:'metrics_below_target',severity:'critical',description:`MRR ${m.mrr_current}<50% of ${m.mrr_target}`,metric:'mrr'});}if(risks.length>0)out.push({id:v.id,name:v.name,stage:v.stage,status:v.status,risks,highest_severity:risks.some(r=>r.severity==='critical')?'critical':'warning'});});return out;}
function listVentures(filters){const f=filters||{};const sb=readSSO('venture_scoreboard.json');const p=readSSO('venture_pipeline.json');let vs=sb.ventures;if(f.stage)vs=vs.filter(v=>v.stage===f.stage);if(f.status)vs=vs.filter(v=>v.status===f.status);return{ventures:vs.map(v=>({id:v.id,name:v.name,stage:v.stage,status:v.status,owner:v.owner_agent,timeline_weeks:v.timeline_weeks,target_mrr:v.target_mrr,created_at:v.created_at,blockers:(v.blockers||[]).length})),total:p.total,active:p.active,killed:p.stages.killed,sources:{ventures:'data/ventures/venture_scoreboard.json',pipeline:'data/ventures/venture_pipeline.json'},timestamp:new Date().toISOString()};}
function createVenture(data){if(!data.name||!data.owner){const e=new Error('Missing required fields: name, owner');e.statusCode=400;throw e;}const id=data.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const sb=readSSO('venture_scoreboard.json');if(sb.ventures.find(v=>v.id===id)){const e=new Error(`Venture already exists: ${id}`);e.statusCode=409;throw e;}const now=new Date().toISOString();const v={id,name:data.name,description:data.description||'',owner_agent:data.owner,owner_human:data.owner_human||'steve',stage:'opportunity',status:'active',created_at:now,timeline_weeks:data.timeline_weeks||8,target_mrr:data.target_mrr||0,target_launch:data.target_launch||null,team:data.team||[data.owner],blockers:[],stage_history:[{stage:'opportunity',entered_at:now,exited_at:null}],metrics:{mrr_target:data.target_mrr||0,mrr_current:0,customer_target:data.customer_target||null,customer_current:0,accuracy_target:data.accuracy_target||null,accuracy_current:null,nps_target:data.nps_target||null,nps_current:null},financials:data.financials||{budget:0,budget_approved:false,burn_rate_weekly:0},artifacts:{memo:data.memo_url||null},market_opportunity:data.market_opportunity||null,kill_date:null,kill_reason:null,kill_decision_maker:null};sb.ventures.push(v);writeSSO('venture_scoreboard.json',sb);try{const full=readSSO('ventures.json');full.ventures.push({...v});writeSSO('ventures.json',full);}catch(_){}try{const wl=readSSO('venture_work_links.json');wl.links.push({venture_id:id,workstream_ids:[]});writeSSO('venture_work_links.json',wl);}catch(_){}recalcPipeline();try{fs.mkdirSync(path.join(VENTURES_DIR,id,'docs'),{recursive:true});fs.mkdirSync(path.join(VENTURES_DIR,id,'tests'),{recursive:true});fs.writeFileSync(path.join(VENTURES_DIR,id,'README.md'),`# ${data.name}\n\n${data.description||''}\n\nStage: opportunity\nOwner: ${data.owner}\n`);}catch(e){console.error('[VENTUREOS] dir:',e.message);}logActivity(`Created venture: ${data.name}`,`"${data.name}" (${id}) created in OPPORTUNITY.`,'info',{venture_id:id,stage:'opportunity'});return{venture_id:id,status:'created',stage:'opportunity',message:`Venture "${data.name}" created in OPPORTUNITY stage.`};}
function advanceStage(venture_id,next_stage){if(!VALID_STAGES.includes(next_stage)){const e=new Error(`Invalid stage: ${next_stage}`);e.statusCode=400;throw e;}const sb=readSSO('venture_scoreboard.json');const idx=sb.ventures.findIndex(v=>v.id===venture_id);if(idx<0){const e=new Error(`Venture not found: ${venture_id}`);e.statusCode=404;throw e;}const v=sb.ventures[idx];const valid=VALID_TRANSITIONS[v.stage]||[];if(!valid.includes(next_stage)){const e=new Error(`Invalid transition: ${v.stage} \u2192 ${next_stage}. Allowed: ${valid.join(', ')}`);e.statusCode=400;throw e;}if(next_stage!=='killed'){const gate=validateGate(v,next_stage);if(!gate.passed){const e=new Error(`Gate preconditions not met for ${next_stage}`);e.statusCode=422;e.missing=gate.missing;e.gate=next_stage;throw e;}}const now=new Date().toISOString();const prev=v.stage;if(!Array.isArray(v.stage_history))v.stage_history=[];const curr=v.stage_history.find(h=>h.exited_at===null);if(curr)curr.exited_at=now;v.stage_history.push({stage:next_stage,entered_at:now,exited_at:null,gate_keeper:GATE_KEEPERS[next_stage]||null});v.stage=next_stage;if(next_stage==='killed')v.status='killed';sb.ventures[idx]=v;writeSSO('venture_scoreboard.json',sb);try{const full=readSSO('ventures.json');const fi=full.ventures.findIndex(fv=>fv.id===venture_id);if(fi>=0){full.ventures[fi].stage=next_stage;full.ventures[fi].stage_history=v.stage_history;if(next_stage==='killed')full.ventures[fi].status='killed';writeSSO('ventures.json',full);}}catch(_){}recalcPipeline();logActivity(`Advanced ${v.name}: ${prev.toUpperCase()} \u2192 ${next_stage.toUpperCase()}`,`Venture "${v.name}" from ${prev} to ${next_stage}.`,'info',{venture_id,from_stage:prev,to_stage:next_stage});return{venture_id,previous_stage:prev,current_stage:next_stage,gate_keeper:GATE_KEEPERS[next_stage]||null,gateway_requirements:getGatewayRequirements(next_stage),message:`Advanced to ${next_stage.toUpperCase()}.`};}
function killVenture(venture_id,reason,decision_maker,notes){if(!KILL_AUTHORIZED.includes((decision_maker||'').toLowerCase())){const e=new Error(`Unauthorized: decision_maker must be one of ${KILL_AUTHORIZED.join(', ')}`);e.statusCode=403;throw e;}if(!reason){const e=new Error('Kill reason is required');e.statusCode=400;throw e;}const sb=readSSO('venture_scoreboard.json');const idx=sb.ventures.findIndex(v=>v.id===venture_id);if(idx<0){const e=new Error(`Venture not found: ${venture_id}`);e.statusCode=404;throw e;}const v=sb.ventures[idx];const prev=v.stage;const now=new Date().toISOString();v.status='killed';v.stage='killed';v.kill_date=now;v.kill_reason=reason;v.kill_decision_maker=decision_maker;if(notes)v.kill_notes=notes;if(!Array.isArray(v.stage_history))v.stage_history=[];const curr=v.stage_history.find(h=>h.exited_at===null);if(curr)curr.exited_at=now;v.stage_history.push({stage:'killed',entered_at:now,exited_at:null,gate_keeper:decision_maker});sb.ventures[idx]=v;writeSSO('venture_scoreboard.json',sb);try{const full=readSSO('ventures.json');const fi=full.ventures.findIndex(fv=>fv.id===venture_id);if(fi>=0){Object.assign(full.ventures[fi],{status:'killed',stage:'killed',kill_date:now,kill_reason:reason,kill_decision_maker:decision_maker});writeSSO('ventures.json',full);}}catch(_){}try{const wl=readSSO('venture_work_links.json');wl.links=wl.links.filter(l=>l.venture_id!==venture_id);writeSSO('venture_work_links.json',wl);}catch(_){}try{const archDir=path.join(VENTURES_DIR,venture_id,'.archive');fs.mkdirSync(archDir,{recursive:true});fs.writeFileSync(path.join(archDir,'kill_record.json'),JSON.stringify({killed_at:now,reason,decision_maker,notes,prev_stage:prev},null,2));}catch(_){}recalcPipeline();logActivity(`Killed venture: ${v.name} (reason: ${reason})`,`Killed by ${decision_maker}. Was in: ${prev}.`,'critical',{venture_id,reason,decision_maker,prev_stage:prev});return{venture_id,status:'killed',killed_at:now,reason,decision_maker,message:'Venture terminated. Resources freed.'};}
function updateMetrics(venture_id,updates){if(!updates||typeof updates!=='object'){const e=new Error('metrics updates object required');e.statusCode=400;throw e;}const sb=readSSO('venture_scoreboard.json');const idx=sb.ventures.findIndex(v=>v.id===venture_id);if(idx<0){const e=new Error(`Venture not found: ${venture_id}`);e.statusCode=404;throw e;}const v=sb.ventures[idx];if(!v.metrics)v.metrics={};const allowed=['accuracy_current','nps_current','customer_current','mrr_current'];const applied={};allowed.forEach(k=>{if(updates[k]!==undefined){v.metrics[k]=updates[k];applied[k]=updates[k];}});v.metrics.metrics_updated_at=new Date().toISOString();sb.ventures[idx]=v;writeSSO('venture_scoreboard.json',sb);try{const full=readSSO('ventures.json');const fi=full.ventures.findIndex(fv=>fv.id===venture_id);if(fi>=0){if(!full.ventures[fi].metrics)full.ventures[fi].metrics={};Object.assign(full.ventures[fi].metrics,applied);full.ventures[fi].metrics.metrics_updated_at=v.metrics.metrics_updated_at;writeSSO('ventures.json',full);}}catch(_){}recalcPipeline();logActivity(`Updated metrics: ${v.name}`,`Metrics updated for "${v.name}": ${JSON.stringify(applied)}`,'info',{venture_id,metrics:applied});return{venture_id,status:'metrics_updated',applied_updates:applied,metrics_snapshot:v.metrics};}
function getPipeline(){const p=readSSO('venture_pipeline.json');return{...p,timestamp:new Date().toISOString()};}
// Backward compat shims for legacy routes
function advanceVenture(slug,next_stage_raw,_actor){try{return{success:true,...advanceStage(slug,(next_stage_raw||'').toLowerCase())};}catch(e){return{success:false,error:e.message,missing:e.missing||[]};}}
function checkKillTriggers(slug){const risks=getAtRisk().filter(v=>v.id===slug);return{triggered:risks.length>0,risks};}
function getAllStageRequirements(){const s={};VALID_STAGES.forEach(stage=>{s[stage]=getGatewayRequirements(stage);});return s;}
module.exports={listVentures,getVentureById,getVentureDetailFull,createVenture,advanceStage,killVenture,updateMetrics,getPipeline,getAtRisk,validateGate,getGatewayRequirements,recalcPipeline,advanceVenture,checkKillTriggers,getAllStageRequirements,getVentureDetail:getVentureDetailFull,_DATA_ROOT:DATA_ROOT,_VALID_STAGES:VALID_STAGES,_VALID_TRANSITIONS:VALID_TRANSITIONS};
